# Generated by Django 4.1.6 on 2023-02-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('gamename', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diceroomid', to='games.room')),
            ],
        ),
        migrations.CreateModel(
            name='Checkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkerroomid', to='games.room')),
            ],
        ),
    ]
