# Generated by Django 4.1.7 on 2023-03-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_room_dice_checkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(max_length=500)),
                ('roomid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobbyroomid', to='games.room')),
            ],
        ),
        migrations.AddField(
            model_name='checkers',
            name='lobby',
            field=models.ManyToManyField(related_name='players_in_lobby', to='games.lobby'),
        ),
    ]
