# Generated by Django 4.1.7 on 2023-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_lobby_checkers_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkers',
            name='openspaces',
            field=models.CharField(default='[[3,1],[3,3],[3,5],[3,7],[4,0],[4,2],[4,4],[4,6]]', max_length=500),
        ),
        migrations.AddField(
            model_name='checkers',
            name='player_one',
            field=models.CharField(default='[[0,0],[0,2],[0,4],[0,6],[1,1],[1,3],[1,5],[1,7],[2,0],[2,2],[2,4],[2,6]]', max_length=500),
        ),
        migrations.AddField(
            model_name='checkers',
            name='playter_two',
            field=models.CharField(default='[[7,1],[7,3],[7,5],[7,7],[6,0],[6,2],[6,4],[6,6],[5,1],[5,3],[5,5],[5,7]]', max_length=500),
        ),
        migrations.AddField(
            model_name='checkers',
            name='team_owner',
            field=models.CharField(default='[AI, AI]', max_length=500),
        ),
    ]
