# Generated by Django 4.1.7 on 2023-03-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_checkers_openspaces_checkers_player_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkers',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkers',
            name='team_owner',
            field=models.CharField(default='AI', max_length=500),
        ),
    ]
