# Generated by Django 4.0.1 on 2023-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('games', '0006_rename_playter_two_checkers_player_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkers',
            name='turn',
            field=models.CharField(default='AI', max_length=500),
        ),
        migrations.AlterField(
            model_name='checkers',
            name='lobby',
            field=models.ManyToManyField(related_name='players_in_lobby', to='games.Lobby'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
