# Generated by Django 4.1.7 on 2023-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_checkers_turn_alter_checkers_lobby_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkers',
            name='kings',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
