# Generated by Django 4.1.7 on 2023-05-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_checkers_kings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monopoly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_owner', models.CharField(default='AI', max_length=500)),
                ('player_one', models.CharField(default='[[0]]', max_length=500)),
                ('player_two', models.CharField(default='[[0]]', max_length=500)),
                ('started', models.BooleanField(default=False)),
                ('turn', models.CharField(default='AI', max_length=500)),
                ('lobby', models.ManyToManyField(related_name='people_in_lobby', to='games.lobby')),
                ('roomid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monopolyroomid', to='games.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Dice',
        ),
    ]
