# Generated by Django 4.1.7 on 2023-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_monopoly_delete_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopoly',
            name='rolled_dice',
            field=models.BooleanField(default=False),
        ),
    ]
