# Generated by Django 4.1.7 on 2023-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_monopoly_rolled_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopoly',
            name='player_four',
            field=models.CharField(default='[[0]]', max_length=500),
        ),
        migrations.AddField(
            model_name='monopoly',
            name='player_three',
            field=models.CharField(default='[[0]]', max_length=500),
        ),
    ]
