# Generated by Django 4.1.7 on 2023-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_monopoly_player_four_monopoly_player_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopoly',
            name='money',
            field=models.CharField(default='[1500,1500,1500,1500]', max_length=500),
        ),
        migrations.AddField(
            model_name='monopoly',
            name='monopolies',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='monopoly',
            name='positions',
            field=models.CharField(default='[0,0,0,0]', max_length=500),
        ),
        migrations.AlterField(
            model_name='monopoly',
            name='player_four',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AlterField(
            model_name='monopoly',
            name='player_one',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AlterField(
            model_name='monopoly',
            name='player_three',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AlterField(
            model_name='monopoly',
            name='player_two',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
